FROM node:20-alpine3.20 as builder

WORKDIR /app
COPY .. .
RUN npm ci
RUN npm run build
RUN npm prune --production 

FROM node:20-alpine3.20 as production

WORKDIR /app

COPY --from=builder /app/node_modules /app/node_modules
COPY --from=builder /app/dist /app
COPY --from=builder /app/prisma /app/prisma
COPY --from=builder /app/.env /app/.env

EXPOSE 3000

CMD ["node", "apps/api/src/app"]
